//! This crate is the binary part of the project [wasm-test](https://github.com/rambip/wasm-test)
//!
//! There is almost no documentation here, consider it is a private API
//!
//! ## Install it
//! ```bash
//! cargo install wasm-test-runner --target <your target>
//! ```
//!
//! ## Use it
//! This binary takes a `.wasm` path as an argument, find all the test_functions inside
//! and run them.
//! The webassembly file must have been generated by wasm-test

use std::env::args;

mod runner;
use runner::run;

use std::process::ExitCode;

fn main() -> ExitCode {
    let args = args().collect::<Vec<String>>();
    let filename = args.get(1).expect("please provide a path");
    println!();
    let success = run(filename);
    if success {
        ExitCode::SUCCESS
    }
    else {
        ExitCode::FAILURE
    }
}
